CREATE TABLE map
(
    id INT NOT NULL AUTO_INCREMENT,
    accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    year SMALLINT NOT NULL,
    data VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    filter VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)
